### ISSUE TITLE
PluginException (compatibility with Rider 2024.1.1)

### ISSUE THREAD

**Issue by kekonn** [Socolin/ApplicationInsightsRiderPlugin#21]
This plugin generates the following exception:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'fr.socolin.applicationinsights.ui.AppInsightsToolWindow$2' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: fr.socolin.application-insights-debug-log-viewer]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

My Rider version info:
```
JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
Licensed to <redacted>
Subscription is active until June 10, 2024.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  com.intellij.bicep (241.14494.150)
  com.github.catppuccin.jetbrains (3.2.3)
  com.intellij.ideolog (222.3.2.0)
  fr.socolin.application-insights-debug-log-viewer (2024.1.2)
  com.intellij.plugin.adernov.powershell (2.6.1)
  com.intellij.ml.llm (241.14494.320)
  com.intellij.bigdatatools.core (241.14494.240)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.14494.240)
  mobi.hsz.idea.gitignore (4.5.3)
  com.intellij.resharper.azure (3.50.0.1773-2024.1)
```

**Comment by centreboard** [comment]
Same messages in 2024.2, for each of `AutoScrollToTheEndToolbarAction`, `ToggleCaseInsensitiveSearchToolbarAction` and `AppInsightsToolWindow$2`

There's some guidance here:
https://plugins.jetbrains.com/docs/intellij/basic-action-system.html#anactiongetactionupdatethread about [background thread (BGT) or the event-dispatching thread (EDT)](https://plugins.jetbrains.com/docs/intellij/threading-model.html)

Should these components all be on EDT as they interact with the UI?

> com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'fr.socolin.applicationinsights.ui.components.AutoScrollToTheEndToolbarAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: fr.socolin.application-insights-debug-log-viewer]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by Socolin** [comment]
Hello,

I've published a new plugin replacing this one. More details are available here: https://github.com/Socolin/ApplicationInsightsRiderPlugin/issues/27

The issue should be fixed
