### ISSUE TITLE
Catch java.lang.NoClassDefFoundError com/intellij/json/JsonLanguage

### ISSUE THREAD

**Issue by devployment** [Socolin/ApplicationInsightsRiderPlugin#25]
Plugin does not work with my current Rider installation. 

JetBrains Rider 2024.3
Build #RD-243.21565.191, built on November 13, 2024

```
Catch java.lang.NoClassDefFoundError com/intellij/json/JsonLanguage

java.lang.NoClassDefFoundError: com/intellij/json/JsonLanguage
at fr.socolin.applicationinsights.ApplicationInsightsSession.addTelemetry(ApplicationInsightsSession.java:119)
at fr.socolin.applicationinsights.ApplicationInsightsSession.lambda$startListeningToOutputDebugMessage$4(ApplicationInsightsSession.java:82)
at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
at com.jetbrains.rd.framework.impl.RdSignal$onWireReceived$2.invoke(RdSignal.kt:33)
at com.jetbrains.rd.framework.impl.RdSignal$onWireReceived$2.invoke(RdSignal.kt:31)
at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:122)
at com.jetbrains.rd.framework.MessageBroker$RdWireableDispatchHelper$doDispatch$2.invoke(MessageBroker.kt:115)
at com.intellij.concurrency.ThreadContext.captureThreadContext$lambda$10(threadContext.kt:425)
at com.intellij.util.concurrency.ContextCallable.lambda$call$0(ContextCallable.java:62)
at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:60)
at com.intellij.concurrency.ThreadContext$captureThreadContext$3.invoke(threadContext.kt:426)
at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:113)
at com.jetbrains.rdclient.protocol.RdDispatcher.flushAllRunnable$lambda$0(RdDispatcher.kt:34)
at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.json.JsonLanguage PluginClassLoader(plugin=PluginDescriptor(name=Application Insights Debug Log Viewer, id=fr.socolin.application-insights-debug-log-viewer, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Rider2024.3/plugins/ApplicationInsights-Debug-Log-Viewer, version=2024.2.0, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/Applications/Rider 2024.3.app/Contents/lib, version=243.21565.191, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/Applications/Rider 2024.3.app/Contents/lib, version=243.21565.191, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/Applications/Rider 2024.3.app/Contents/lib, version=243.21565.191, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.rider, descriptorPath=intellij.rider.xml, path=~/Applications/Rider 2024.3.app/Contents/lib, version=243.21565.191, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/Applications/Rider 2024.3.app/Contents/lib, version=243.21565.191, package=null, isBundled=true), )
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
... 59 more
```

**Comment by Socolin** [comment]
You can try the version available https://github.com/Socolin/ApplicationInsightsRiderPlugin/actions/runs/11881644152

The plugin update is blocked on Jetbrains side because some API I'm using in the plugin are now marked as Internal and I need to find the replacement, for now you can use the `.zip`  to install the plugins.

**Comment by klawrow** [comment]
Thanks @Socolin! The artifact worked for me in 2024.3.

**Comment by klawrow** [comment]
Spoke too soon. The plugin launches, but no events are tracked 😭

**Comment by Socolin** [comment]
I'll take a look.

Do you have any logs related to this ?

**Comment by klawrow** [comment]
Where in particular would the logs be? I'm not seeing any exceptions.

![Screenshot 2024-11-19 at 23 27 11](https://github.com/user-attachments/assets/364b4eb1-b7ab-4975-aa23-276e3f90bc4e)

**Comment by Socolin** [comment]
Check in the idea.log (look in the help menu or there is an ction Show logs in files I think)

**Comment by devployment** [comment]
Seems to work for me. Thanks a lot.

**Comment by Socolin** [comment]
So I checked and it's strange, I don't have it when I run from ./gradlew :runIde but I have the error when I package it add it to the install from the toolbox. Seems the dependency is not enable / or something in some case.

**Comment by Socolin** [comment]
@klawrow can you try this build ? https://github.com/Socolin/ApplicationInsightsRiderPlugin/actions/runs/12019385625

**Comment by klawrow** [comment]
> @klawrow can you try this build ? https://github.com/Socolin/ApplicationInsightsRiderPlugin/actions/runs/12019385625

Testing, will keep you posted.

**Comment by klawrow** [comment]
@Socolin figured out what happened, I forgot to switch my launch profile 🤦‍♂️.

My default profile is basically an HttpWatch so I can get hot-reload to work properly. After switching to the regular profile, the extension worked like a charm.

<img width="774" alt="Screenshot 2024-11-26 at 02 14 38" src="https://github.com/user-attachments/assets/a67fa3d4-1f1c-45cd-b08a-a8f577990f29">
